name: CI
on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 22.x

      - name: Install pnpm
        run: npm install -g pnpm@9
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Run E2E Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pnpm test:vscode
      - name: Run Tests
        run: pnpm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 22.x

      - name: Install pnpm
        run: npm install -g pnpm@9
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Linter
        run: pnpm run lint
